import type { LevelConfig, SceneObject } from "./types";

export const TIDY_TOYS_DRAG: LevelConfig = {
  id: "tidy_toys_drag",
  title: "Tidy up the toys (simple drag)",
  type: "drag_to_target",
  instructions: "Drag every toy into the toy box",
  theme: "living_room",
  objects: [
    {
      id: "ball",
      label: "Ball",
      asset: "ball",
      color: "red",
      x: 18,
      y: 58,
      size: 18,
      targetId: "toy_box",
    },
    {
      id: "blocks",
      label: "Blocks",
      asset: "blocks",
      color: "blue",
      x: 48,
      y: 66,
      size: 18,
      targetId: "toy_box",
    },
    {
      id: "doll",
      label: "Doll",
      asset: "doll",
      color: "yellow",
      x: 20,
      y: 82,
      size: 18,
      targetId: "toy_box",
    },
    {
      id: "dino",
      label: "Dino",
      asset: "dino",
      color: "green",
      x: 50,
      y: 86,
      size: 18,
      targetId: "toy_box",
    },
  ],
  targets: [{ id: "toy_box", label: "Toys", shape: "box", x: 80, y: 78, w: 32, h: 20 }],
  success: { kind: "all_placed" },
  monster: { trigger: "on_complete", intervention: "none" },
  personalization: { source: "none", transform: "none" },
};

const slot = (id: string, color: SceneObject["color"], x: number, y: number): SceneObject => ({
  id,
  label: "Toy",
  asset: "ball",
  color,
  x,
  y,
  size: 17,
  targetId: "toy_box",
});

export const TIDY_TOYS: LevelConfig = {
  id: "tidy_toys",
  title: "Tidy up the toys",
  type: "tidy_roles",
  instructions: "Put every toy in the toy box",
  theme: "living_room",
  objects: [
    slot("toy_1", "red", 16, 60),
    slot("toy_2", "blue", 44, 64),
    slot("toy_3", "yellow", 16, 84),
    slot("toy_4", "green", 44, 86),
    slot("toy_5", "purple", 70, 56),
  ],
  targets: [{ id: "toy_box", label: "Toys", shape: "box", x: 80, y: 80, w: 30, h: 18 }],
  success: { kind: "all_placed" },
  monster: { trigger: "on_complete", intervention: "none" },
  personalization: { source: "none", transform: "none" },
  tidy: {
    seed: null,
    pool: ["ball", "blocks", "doll", "dino", "teddy", "car", "robot", "book"],
    steps: [
      { role: "plain", hint: "Drag the toys into the box" },
      { role: "cushion", hint: "Something slipped under the cushion…" },
      { role: "drawer", hint: "Did the drawer just close?" },
      { role: "plain", hint: "Almost done…" },
      { role: "plain", hint: "One more." },
    ],
    cushion: { x: 50, y: 44 },
    drawer: { x: 18, y: 40 },
    completeLine: "You put them all away. Now it's my turn to ask.",
  },
};

export const SET_TABLE: LevelConfig = {
  id: "set_table",
  title: "Set the table",
  type: "place_items",
  instructions: "Put each thing in its spot on the table",
  theme: "dining_room",
  objects: [
    {
      id: "plate",
      label: "Plate",
      asset: "plate",
      color: "yellow",
      x: 16,
      y: 84,
      size: 18,
      targetId: "spot_plate",
    },
    {
      id: "glass",
      label: "Glass",
      asset: "glass",
      color: "red",
      x: 39,
      y: 84,
      size: 18,
      targetId: "spot_glass",
    },
    {
      id: "fork",
      label: "Fork",
      asset: "fork",
      color: "blue",
      x: 62,
      y: 84,
      size: 18,
      targetId: "spot_fork",
    },
    {
      id: "napkin",
      label: "Napkin",
      asset: "napkin",
      color: "green",
      x: 85,
      y: 84,
      size: 18,
      targetId: "spot_napkin",
    },
  ],
  targets: [
    { id: "spot_fork", label: "Fork", shape: "rect", x: 24, y: 42, w: 16, h: 20 },
    { id: "spot_plate", label: "Plate", shape: "circle", x: 50, y: 42, w: 26, h: 20 },
    { id: "spot_glass", label: "Glass", shape: "circle", x: 76, y: 32, w: 18, h: 14 },
    { id: "spot_napkin", label: "Napkin", shape: "rect", x: 76, y: 52, w: 18, h: 14 },
  ],
  success: { kind: "all_placed" },
  monster: { trigger: "after_half", intervention: "disturb_item" },
  personalization: { source: "favorite_color", transform: "color_removed" },
};

export const BEDTIME: LevelConfig = {
  id: "bedtime",
  title: "Bedtime",
  type: "flashlight_find",
  instructions: "Drag the flashlight. Tap what you find.",
  theme: "bedroom",
  objects: [
    {
      id: "pajamas",
      label: "Pajamas",
      asset: "pajamas",
      color: "pink",
      x: 20,
      y: 30,
      size: 16,
      targetId: "",
    },
    {
      id: "toothbrush",
      label: "Toothbrush",
      asset: "toothbrush",
      color: "blue",
      x: 80,
      y: 74,
      size: 16,
      targetId: "",
    },
    {
      id: "toy",
      label: "Your toy",
      asset: "teddy",
      color: "orange",
      x: 72,
      y: 28,
      size: 18,
      targetId: "",
    },
  ],
  targets: [],
  success: { kind: "all_placed" },
  monster: { trigger: "on_complete", intervention: "none" },
  personalization: { source: "favorite_toy", transform: "toy_shadow" },
  flashlight: {
    radius: 24,
    evasive: {
      objectId: "toy",
      positions: [
        { x: 22, y: 82 },
        { x: 50, y: 56 },
        { x: 82, y: 50 },
      ],
      whisper: "Not there. It doesn't want to sleep with you anymore…",
    },
  },
};

export const BUILT_IN_LEVELS: LevelConfig[] = [TIDY_TOYS, SET_TABLE, BEDTIME, TIDY_TOYS_DRAG];

/** Which level plays at each task stage of the main story. */
export const STORY_LEVELS = {
  task_one: TIDY_TOYS,
  task_two: SET_TABLE,
  task_three: BEDTIME,
} as const;
